import React from "react";
import {
  FaRegFileAlt,
  FaStream,
  FaGopuram,
  FaHome,
  FaCircle,
  FaProductHunt,
} from "react-icons/fa";
import * as Icon from "react-feather";

// eslint-disable-next-line no-sparse-arrays
const navigationConfig = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "item",
    icon: <FaHome size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/dashboard",
  },
  {
    type: "groupHeader",
    groupTitle: "Stock Manager",
  },
  {
    id: "product_attribute",
    title: "Product Management",
    type: "collapse",
    icon: <FaProductHunt size={15} />,
    children: [
      {
        id: "Attribute",
        title: "Attribute",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/options/AttributeList",
      },
      {
        id: "productlist",
        title: "ProductList",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/house/houseProductList",
      },
      {
        id: "bundlelist",
        title: "Bundle",
        type: "item",
        icon: <FaGopuram size={15} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/bundle/BundleList",
      },
    ],
  },
  {
    id: "categorys",
    title: "Category Management",
    type: "collapse",
    icon: <FaStream size={15} />,
    children: [
      {
        id: "addCategory",
        title: "Add Category",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/category/addCategory",
      },
      {
        id: "Category",
        title: "Category",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/category/categoryList",
      },
    ],
  },
  {
    id: "Warehouses",
    title: "Warehouse Management",
    type: "collapse",
    icon: <FaHome size={15} />,
    permissions: ["admin", "editor"],
    children: [
      {
        id: "createwarehouse",
        title: "Create Warehouse",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/warehouse/createWarehouse",
      },
      {
        id: "warehouse",
        title: "Warehouse",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/warehouse/warehouseList",
      },
    ],
  },
  {
    id: "PurchaseOrder",
    title: "Purchase Order",
    type: "item",
    icon: <Icon.ShoppingCart size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/order/all",
  },
  {
    id: "SuppliersManagement",
    title: "Suppliers Management",
    type: "item",
    icon: <Icon.User size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/vendor/vendorList",
  },
  {
    id: "dashboard",
    title: "Stock Return",
    type: "item",
    icon: <Icon.Layers size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/house/houseProductList",
  },
  {
    id: "dashboard",
    title: "Stock Return (Customer)",
    type: "item",
    icon: <Icon.Layers size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/house/houseProductList",
  },
  {
    id: "dashboard",
    title: "Stock Transfer",
    type: "item",
    icon: <Icon.Layers size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/house/houseProductList",
  },
  {
    type: "groupHeader",
    groupTitle: "Sales",
  },
  {
    id: "StandardInvoice",
    title: "Standard invoice",
    type: "item",
    icon: <Icon.FileText size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/invoices/InvoicesList",
  },
  {
    id: "quotesManagement",
    title: "Quotes Management",
    type: "item",
    icon: <Icon.FileMinus size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/quote/QuoteList",
  },
  {
    id: "creditNotes",
    title: "Credit Notes",
    type: "item",
    icon: <Icon.CreditCard size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/credit/CreditList",
  },
  {
    type: "groupHeader",
    groupTitle: "Finance",
  },
  {
    id: "accountManagement",
    title: "Account Management",
    type: "collapse",
    icon: <Icon.User size={15} />,
    children: [
      {
        id: "accountsManagement",
        title: "Account Management",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/accounts/AccountsList",
      },
      {
        id: "transectionsManagement",
        title: "Transection Management",
        type: "item",
        icon: <Icon.DollarSign size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/transactions/TransectionsList",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Hrm",
  },
  {
    id: "Employee",
    title: "Employee Management",
    type: "collapse",
    icon: <Icon.Users size={15} />,
    permissions: ["admin", "editor"],
    children: [
      {
        id: "addEmployee",
        title: "Add Employee",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/employee/addEmployee",
      },
      {
        id: "delivery",
        title: "Employees",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/employee/employeesList",
      },
    ],
  },
  {
    id: "Departments",
    title: "Departments",
    type: "collapse",
    icon: <Icon.Codepen size={15} />,
    permissions: ["admin", "editor"],
    children: [
      {
        id: "addDepartment",
        title: "Add Department",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/department/addDepartment",
      },
      {
        id: "Department",
        title: "Department",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/department/departmentList",
      },
    ],
  },
  {
    id: "payroll",
    title: "Payroll",
    type: "collapse",
    icon: <Icon.CreditCard size={15} />,
    permissions: ["admin", "editor"],
    children: [
      {
        id: "addPayroll",
        title: "Add Payroll",
        type: "item",
        icon: <Icon.CreditCard size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/payroll/addPayroll",
      },
      {
        id: "Payrolls",
        title: "Payrolls",
        type: "item",
        icon: <Icon.CreditCard size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/payroll/payrollList",
      },
    ],
  },
  {
    id: "refund",
    title: "Attendance",
    type: "collapse",
    icon: <FaRegFileAlt size={15} />,
    children: [
      {
        id: "Attendance",
        title: "Attendance",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/attendance/attendanceList",
      },
      {
        id: "holiday",
        title: "Holiday/Leave Management",
        type: "item",
        icon: <FaCircle size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/holiday/holidayList",
      },
    ],
  },
  {
    type: "groupHeader",
    groupTitle: "Staff",
  },
  {
    id: "staffDepartments",
    title: "Departments",
    type: "collapse",
    icon: <Icon.Users size={15} />,
    permissions: ["admin", "editor"],
    children: [
      {
        id: "staffaddDepartment",
        title: "Add Department",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/staff/department/addDepartment",
      },
      {
        id: "staffDepartment",
        title: "Department",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/staff/department/departmentList",
      },
    ],
  },
  {
    id: "employeesStaff",
    title: "Employee",
    type: "collapse",
    icon: <Icon.Users size={15} />,
    permissions: ["admin", "editor"],
    children: [
      {
        id: "addEmployeeStaff",
        title: "Add Employee",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/staff/employee/addEmployee",
      },
      {
        id: "employeeStaff",
        title: "Employees",
        type: "item",
        icon: <Icon.User size={8} />,
        permissions: ["admin", "editor"],
        navLink: "/app/freshlist/staff/employee/employeesList",
      },
    ],
  },
  {
    id: "dashboard",
    title: "Role Assign",
    type: "item",
    icon: <Icon.Award size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/house/houseProductList",
  },
  {
    id: "dashboard",
    title: "Permission Set",
    type: "item",
    icon: <Icon.Settings size={15} />,
    permissions: ["admin", "editor"],
    navLink: "/app/freshlist/house/houseProductList",
  },
  // {
  //   id: "dashboard",
  //   title: "DASHBOARD",
  //   type: "item",
  //   icon: <FaHome size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/",
  // },
  // {
  //   id: "order",
  //   title: "Orders",
  //   type: "collapse",
  //   icon: <FaShoppingCart size={15} />,
  //   children: [
  //     {
  //       id: "all",
  //       title: "All  (50)",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/order/all",
  //     },
  //     {
  //       id: "pending ",
  //       title: "Pending  (10)",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/order/pending",
  //     },
  //     {
  //       id: "confirmed",
  //       title: "Confirmed (12)",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/order/confirmed",
  //     },
  //     {
  //       id: "inprocess ",
  //       title: "In Process (17)",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/order/inprocess",
  //     },
  //     {
  //       id: "outfordelivery",
  //       title: "Out for delivery (09)",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/order/outfordelivery",
  //     },
  //     {
  //       id: "delivery",
  //       title: "Delivered (20)",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/order/delivered",
  //     },
  //     {
  //       id: "return",
  //       title: "Returned (07)",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/order/returned",
  //     },
  //     {
  //       id: "failedtodeliver",
  //       title: "Failed to Deliver",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/order/failedtodeliver",
  //     },
  //     // {
  //     //   id: "canceled",
  //     //   title: "Canceled (00)",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/order/canceled",
  //     // },
  //   ],
  // },
  // {
  //   id: "refund",
  //   title: "Refund Requests",
  //   type: "collapse",
  //   icon: <FaRegFileAlt size={15} />,
  //   children: [
  //     {
  //       id: "pending",
  //       title: "Pending",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/refundrequest/pendingRequest",
  //     },
  //     {
  //       id: "approv",
  //       title: "Approved",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/refundrequest/approvedRequest",
  //     },

  //     {
  //       id: "comp",
  //       title: "Completed",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/refundrequest/completedRequest",
  //     },
  //     {
  //       id: "reject",
  //       title: "Rejected",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/refundrequest/rejectedRequest",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "PRODUCT MANAGEMENT",
  // },
  // {
  //   id: "brand",
  //   title: "Brand",
  //   type: "collapse",
  //   icon: <FaStar size={15} />,
  //   children: [
  //     {
  //       id: "brandlist",
  //       title: "Brand List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/brand/BrandList",
  //     },
  //   ],
  // },
  // {
  //   id: "batch",
  //   title: "Batch",
  //   type: "collapse",
  //   icon: <FaStar size={15} />,
  //   children: [
  //     {
  //       id: "batchList",
  //       title: "Batch List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/batch/batchList",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "CUSTOMER MANAGEMENT",
  // },
  // {
  //   id: "customer",
  //   title: "Customers  ",
  //   type: "collapse",
  //   icon: <FaWallet size={15} />,
  //   children: [
  //     {
  //       id: "customergroup",
  //       title: "Customer Group",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/customer/customergroup",
  //     },
  //     {
  //       id: "list",
  //       title: "Customer List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/customer/customerList",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "CATEGORY MANAGEMENT",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Delivery Control MANAGEMENT",
  // },
  // {
  //   id: "deliveryslots",
  //   title: "Delivery Slots",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },
  // {
  //   id: "holiday",
  //   title: "Holiday Management",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },
  // {
  //   id: "weekdays",
  //   title: "Weekdays",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },
  // {
  //   id: "Export&Import",
  //   title: "BULK Export And Import",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Wallet Management",
  // },
  // {
  //   id: "wallet",
  //   title: "Wallet",
  //   type: "collapse",
  //   icon: <FaCircle size={8} />,
  //   children: [
  //     {
  //       id: "credit",
  //       title: "Credit/Debit",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/wallet/walletType",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "DRIVER MANAGEMENT",
  // },
  // {
  //   id: "driver",
  //   title: "Driver",
  //   type: "collapse",
  //   icon: <FaUser size={15} />,
  //   children: [
  //     {
  //       id: "addriver",
  //       title: "Add Driver",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/driver/addDriver",
  //     },
  //     {
  //       id: "driverList",
  //       title: "Driver List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/driver/driverList",
  //     },
  //   ],
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "SUBSCRIPTIONS MANAGEMENT",
  // },
  // {
  //   id: "subscriptions",
  //   title: "Subscriptions",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/subscriber/subscriberList",
  // },
  // {
  //   id: "vendor",
  //   title: "Vendors",
  //   type: "collapse",
  //   icon: <FaUsers size={15} />,
  //   children: [
  //     // {
  //     //   id: "vendor",
  //     //   title: "Add Vendors  ",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/vendor/addVendor",
  //     // },
  //     {
  //       id: "vendor_list",
  //       title: "Vendors List",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/vendor/vendorList",
  //     },
  //     {
  //       id: "withdraw",
  //       title: "Withdraws",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/vendor/withDraws",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Hub MANAGEMENT",
  // },
  // {
  //   id: "hub",
  //   title: "Hub",
  //   type: "collapse",
  //   icon: <FaShoppingCart size={15} />,
  //   children: [
  //     // {
  //     //   id: "addhub",
  //     //   title: "AddHub",
  //     //   type: "item",
  //     //   icon: <FaCircle size={8} />,
  //     //   permissions: ["admin", "editor"],
  //     //   navLink: "/app/freshlist/hubs/addhub",
  //     // },
  //     {
  //       id: "hubList",
  //       title: "HubList",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/hubs/hubList",
  //     },
  //   ],
  // },
  // {
  //   id: "language",
  //   title: "Language",
  //   type: "item",
  //   icon: <FaCircle size={8} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/language/languageList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Web Banner Management",
  // },
  // {
  //   id: "homepage",
  //   title: "Home Page",
  //   type: "item",
  //   icon: <BsImage size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/banner/BannerList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Mobile App Management",
  // },
  // {
  //   id: "bannerSection",
  //   title: "Banner with section Colours",
  //   type: "item",
  //   icon: <GiWantedReward size={18} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/mobile/bannerSection",
  // },
  // {
  //   id: "notification",
  //   title: "Notification",
  //   type: "collapse",
  //   icon: <GiWantedReward size={18} />,
  //   children: [
  //     {
  //       id: "all",
  //       title: "All",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/mobile/allNotify",
  //     },
  //     {
  //       id: "customerGroupWise",
  //       title: "Customer Group Wise",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/mobile/customerGroupWise",
  //     },
  //   ],
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: " Banner Management",
  // },
  // {
  //   id: "Banner",
  //   title: "Banner",
  //   type: "item",
  //   icon: <BsImage size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/banner/BannerList",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "PROMOTION MANAGEMENT",
  // },

  // {
  //   id: "special",
  //   title: "Special",
  //   type: "item",
  //   icon: <MdOutlineFolderSpecial size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/special/SpecialList",
  // },
  // {
  //   id: "discount",
  //   title: "Discount",
  //   type: "item",
  //   icon: <CiDiscount1 size={18} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/discount/DiscountList",
  // },
  // {
  //   id: "reward_point",
  //   title: "Reward Point",
  //   type: "item",
  //   icon: <GiWantedReward size={18} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/points/points",
  // },

  // {
  //   id: "offer&deal",
  //   title: "Offers & Deals",
  //   type: "collapse",
  //   icon: <FaUsers size={15} />,
  //   children: [
  //     {
  //       id: "couponcode",
  //       title: "Coupon Code",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/coupon/couponList",
  //     },
  //     {
  //       id: "flashSale",
  //       title: "Referal Code",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/flashSale/flashSale",
  //     },
  //     {
  //       id: "dealOfDay",
  //       title: "Hub Delivery",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/dealOfDay/DealOfDay",
  //     },
  //     {
  //       id: "featuredeal",
  //       title: " Pin Code",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/featuredeal/featuredeal",
  //     },
  //     {
  //       id: "notification",
  //       title: "Delivery Cities",
  //       type: "item",
  //       icon: <GiWantedReward size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/notif/notification",
  //     },
  //   ],
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "ZONE MANAGEMENT",
  // },
  // {
  //   id: "deliveryCharges",
  //   title: "DeliveryCharges",
  //   type: "item",
  //   icon: <FaStar size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/zone/AddDeliveryCharges",
  // },

  // {
  //   id: "addzone",
  //   title: "Add Zone",
  //   type: "item",
  //   icon: <TbTruckDelivery size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/zone/addzone",
  // },
  // {
  //   id: "zoneslist",
  //   title: "ZonesList",
  //   type: "item",
  //   icon: <TbTruckDelivery size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/zone/zoneslist",
  // },

  // {
  //   id: "taxreport",
  //   title: "Tax Report  ",
  //   type: "item",
  //   icon: <FiBarChart2 size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/report/taxReport",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Report MANAGEMENT",
  // },

  // {
  //   id: "sales",
  //   title: "Sales",
  //   type: "collapse",
  //   icon: <FaWallet size={15} />,
  //   children: [
  //     {
  //       id: "totalSales",
  //       title: "Total Sale",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/sales/totalSales",
  //     },
  //     {
  //       id: "hubSales",
  //       title: "Hub Sale",
  //       type: "item",
  //       icon: <FaCircle size={8} />,
  //       permissions: ["admin", "editor"],
  //       navLink: "/app/freshlist/sales/hubSales",
  //     },
  //   ],
  // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Pages & MEDIA MANAGEMENT",
  // },
  // {
  //   id: "gallery",
  //   title: "Gallery",
  //   type: "item",
  //   icon: <TbTruckDelivery size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/gallery/gallery",
  // },
  // {
  //   id: "term & condition",
  //   title: "Term & Condition",
  //   type: "item",
  //   icon: <FaFileSignature size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/termsAndCondition/TAndCList",
  // },
  // // {
  // //   type: "groupHeader",
  // //   groupTitle: "Option MANAGEMENT",
  // // },
  // // {
  // //   id: "attributelist",
  // //   title: "AttributeList",
  // //   type: "item",
  // //   icon: <FaCircle size={15} />,
  // //   permissions: ["admin", "editor"],
  // //   navLink: "/app/freshlist/options/AttributeList",
  // // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "USER MANAGEMENT",
  // },
  // // {
  // //   id: "employee",
  // //   title: "Employee",
  // //   type: "collapse",
  // //   icon: <FaUser size={15} />,
  // //   children: [
  // {
  //   id: "setup",
  //   title: "Manage Role",
  //   type: "item",
  //   icon: <FaCircle size={8} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/user/manageRole",
  //   // navLink: "/app/freshlist/user/customsetuprole",
  // },
  // {
  //   id: "manageUsers",
  //   title: "Manage Users",
  //   type: "item",
  //   icon: <FaCircle size={8} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/user/userlist",
  //   // navLink: "/app/freshlist/user/employeeslist",
  // },
  // //   ],
  // // },

  // {
  //   type: "groupHeader",
  //   groupTitle: "Freebies MANAGEMENT",
  // },
  // {
  //   id: "manageFreebies",
  //   title: "Manage Freebies",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/freebies/freebies",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "Cart MANAGEMENT",
  // },
  // {
  //   id: "suggestedProducts",
  //   title: "Suggested Products",
  //   type: "item",
  //   icon: <FaUser size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/cart/suggestedProducts",
  // },
  // {
  //   type: "groupHeader",
  //   groupTitle: "SUPPORT MANAGEMENT",
  // },

  // {
  //   id: "privacypolicy",
  //   title: "Privacy Policy",
  //   type: "item",
  //   icon: <FaCog size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/privacyPolicy/privacyPolicy",
  // },
  // {
  //   id: "helpAndSupport",
  //   title: "Help And Support",
  //   type: "item",
  //   icon: <FaQuestionCircle size={15} />,
  //   permissions: ["admin", "editor"],
  //   navLink: "/app/freshlist/helpAndSupport/helpAndSupport",
  // },
  // {
  //   id: "logout",
  //   title: "Logout",
  //   type: "item",
  //   icon: <Icon.ArrowRight size={15} />,
  //   permissions: ["admin", "editor"],
  // },

  // // {
  // //   id: "subscription",
  // //   title: "Subscriptions",
  // //   type: "item",
  // //   // icon: <Icon.Youtube size={20} />,
  // //   permissions: ["admin", "editor"],
  // //   navLink: "/app/marketing/subscription/subscriptionList",
  // // },
  // // {
  // //   id: "invoiceSetting",
  // //   title: "Invoice Setting ",
  // //   type: "item",
  // //   icon: < FaCircle size={12}/>,
  // //   permissions: ["admin", "editor"],
  // //   navLink: "/app/order/invoiceSetting",
  // // },
  // // {
  // //   id: "invoiceDesign",
  // //   title: "Invoice Design ",
  // //   type: "item",
  // //   icon: < FaCircle size={12}/>,
  // //   permissions: ["admin", "editor"],
  // //   navLink: "/app/order/invoiceDesign",
  // // },
  // // {
  // //   id: "bank",
  // //   title: "Bank",
  // //   type: "collapse",
  // //    icon: < FaHouseDamage size={20} />,
  // //    children: [
  // //     {
  // //       id: "bank",
  // //       title: "bank Details",
  // //       type: "item",
  // //       icon: < FaCircle size={12}/>,
  // //       permissions: ["admin", "editor"],
  // //       navLink: "/app/bank/bank",
  // //     },
  // //   ]
  // // },
  // //     {
  // //       id: "pushnotification",
  // //       title: "Push Notification",
  // //       type: "item",
  // //       icon: < FaCircle size={12}/>,
  // //       permissions: ["admin", "editor"],
  // //       navLink: "/app/marketing/pushnotification/addPushnotification",
  // //     },

  // //      {
  // //        id: "variantList",
  // //        title: "Variant",
  // //        type: "item",
  // //        icon: <Icon.Circle size={12} />,
  // //        permissions: ["admin", "editor"],
  // //        navLink: "/app/productManagement/variant/variantList",
  // //      },
  // //      {
  // //        id: "unitsList",
  // //        title: "Units",
  // //        type: "item",
  // //        icon: <Icon.Circle size={12} />,
  // //        permissions: ["admin", "editor"],
  // //        navLink: "/app/productManagement/units/unitsList",
  // //     },
];
export default navigationConfig;
